name: "🚔"

on:
  push

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:

      - name: Git
        uses: actions/checkout@v2

      - name: Java
        uses: actions/setup-java@v2.3.0
        with:
          distribution: 'adopt'
          java-version: '16'

      - name: Cache
        uses: actions/cache@v3.0.1
        with:
          path: ~/.m2
          key: '${{ runner.os }}-m2-${{ hashFiles(''**/pom.xml'') }}'
          restore-keys: '${{ runner.os }}-m2'

      - name: Verify
        run: mvn --batch-mode --show-version --errors verify --file pom.xml
